name: Backend Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install --upgrade -r Backend/requirements.txt
    - name: Print Python Info
      run: |
        python --version
        pip list

    - name: change 
      run:  cd Backend
      
    - name: run tests
      run:  pytest Backend/test_app.py 
        
