name: Backend Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install --upgrade -r Backend/requirements.txt
    - name: Print Python Info
      run: |
        python --version
        pip list

    - name: change 
      run:  cd Backend
      
    - name: run tests
      run:  pytest Backend/test_app.py
    
    - name: Execute app.py
      run: python Backend/app.py &
      env:
        PORT: 5001  

    - name: Wait for app to start
      run: sleep 5

    - name: Check if app is running
      run: curl http://localhost:$PORT

    - name: Kill the app
      run: pkill -f "python app.py" 
        
