name: Docker Build Backend Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: backend/Dockerfile

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest backend

    - name: Push the Docker image to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
